version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-fmd
    restart: always
    ports:
      - 6379:6379
    volumes:
      - my-data:/var/lib/redis

  app:
    image: kkamacoon/fmd-dev
    container_name: fmd-dev
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  my-data: