name: FMD-CD

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker-compose -f docker-compose.prod.yaml down --rmi all 
            docker pull ${{ secrets.DOCKER_USERNAME }}/fmd-prod:latest
            docker-compose -f docker-compose.prod.yaml up -d

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        if: contains(github.ref, 'develop')
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker-compose -f docker-compose.dev.yaml down --rmi all
            docker pull ${{ secrets.DOCKER_USERNAME }}/fmd-dev:latest
            docker-compose -f docker-compose.dev.yaml up -d
